import type { Metadata } from "next";
import { Baloo_2 as FontSans } from "next/font/google";
import { ViewTransitions } from "next-view-transitions";

import "@/styles/globals.css";

import NextTopLoader from "nextjs-toploader";

import { initActions } from "@/lib/actions";
import { cn } from "@/lib/utils";
import { TRPCProvider } from "@/providers/trpc-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await initActions(); // dirty hack to avoid await top-level issue with server actions in Next.js
  return (
    <ViewTransitions>
      <html lang="es" className={cn(fontSans.variable)}>
        <body className={cn("overflow-hidden")}>
          <NextTopLoader color="#65C4BC" showSpinner={false} />
          <TRPCProvider>{children}</TRPCProvider>
        </body>
      </html>
    </ViewTransitions>
  );
}
