import {
  IconBabyBottle,
  IconBrandTrello,
  IconBuildingStore,
  IconCategory,
  IconCategory2,
  IconChevronLeft,
  IconChevronRight,
  IconInfoOctagon,
  IconLayoutDashboard,
  IconLogin2,
  IconLogout,
  IconPalette,
  IconPassword,
  IconRuler2,
  IconShield,
  IconTrash,
  IconUser,
  IconUserEdit,
  IconUsersGroup,
  IconUserStar,
  IconX,
  TablerIcon,
} from "@tabler/icons-react";

export type Icon = TablerIcon;

export const Icons = {
  dashboard: IconLayoutDashboard,
  login: IconLogin2,
  logout: IconLogout,
  close: IconX,
  product: IconBabyBottle,
  kanban: IconBrandTrello,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  password: IconPassword,
  user: IconUser,
  usersGroup: IconUsersGroup,
  userEdit: IconUserEdit,
  addAdmin: IconUserStar,
  item: IconInfoOctagon,
  privacy: IconShield,
  store: IconBuildingStore,
  category: IconCategory,
  subcategory: IconCategory2,
  size: IconRuler2,
  color: IconPalette,
  mundobebe: null,
};
